---
title: "Calculate Chebyshev Center"
author: "B Steele"
format: html
jupyter: python3
---

Adapted from 

Yang, Xiao. (2020). Deepest point calculation for any given polygon using Google Earth Engine JavaScript API (Version v2). Zenodo. https://doi.org/10.5281/zenodo.6341960

var getUTMProj = function(lon, lat) {
  // see https://apollomapping.com/blog/gtm-finding-a-utm-zone-number-easily and
  // https://sis.apache.org/faq.html
  var utmCode = ee.Number(lon).add(180).divide(6).ceil().int();
  var output = ee.Algorithms.If(ee.Number(lat).gte(0),
  ee.String('EPSG:326').cat(utmCode.format('%02d')),
  ee.String('EPSG:327').cat(utmCode.format('%02d')));
  return(output);
};
var GetLakeCenters = function(polygon, scale) {
  // calculate the deepest point for the inpout polygon (or multipolygon)
  // for each input, export the deepest point and its distance to shore.

  var ct = polygon.centroid(scale);
  var utmCode = getUTMProj(ct.coordinates().getNumber(0), ct.coordinates().getNumber(1));

  var polygonImg = ee.Image.constant(1).toByte().paint(ee.FeatureCollection(ee.Feature(polygon, null)), 0);

  var dist = polygonImg.fastDistanceTransform(2056).updateMask(polygonImg.not())
  .sqrt().reproject(utmCode, null, scale).multiply(scale); // convert unit from pixel to meter

  var maxDistance = dist.reduceRegion({
    reducer: ee.Reducer.max(),
    geometry: polygon,
    scale: scale,
    bestEffort: true,
    tileScale: 1
  }).getNumber('distance');

  var outputDp = ee.Feature(dist.addBands(ee.Image.pixelLonLat()).updateMask(dist.gte(maxDistance))
  .sample(polygon, scale).first());
  var dp = ee.Geometry.Point([outputDp.get('longitude'), outputDp.get('latitude')]);

  var regions = ee.FeatureCollection([ee.Feature(dp, {'type': 'dp'})]);

  var output = dist.sampleRegions({
    collection: regions,
    properties: ['type'],
    scale: scale,
    tileScale: 1,
    geometries: true});

  return(ee.Feature(output.first()));
};

// test
// uncomment the following lines to see an example.
// var aoi = /* color: #d63000 */ee.Geometry.Polygon(
//         [[[-115.6345703125, 46.96878170269706],
//           [-116.7771484375, 44.57849399879169],
//           [-112.5583984375, 42.54069509819464],
//           [-111.3279296875, 45.324883450915685],
//           [-110.4490234375, 47.8018637457304],
//           [-114.0525390625, 44.703566335526844],
//           [-114.0525390625, 47.028724354732496],
//           [-115.3708984375, 47.74279437445949]]]);
// Map.centerObject(aoi);
// Map.addLayer(aoi);
// Map.addLayer(GetLakeCenters(aoi, 1000).aside(print))
